/**
 * realData.ts — Real data integration layer
 *
 * Loads merged holdings data from /data/merged_holdings.json (generated by scrapers).
 * Falls back gracefully to mock data if no real data file exists.
 *
 * Data sources:
 *   - SEC EDGAR 13F-HR (US stocks) → data/holdings_latest.json
 *   - HKEX Disclosure (HK stocks)  → data/hk_holdings.json
 *   - Eastmoney QFII (CN A-shares) → data/qfii_holdings.json
 *   - Merged output               → data/merged_holdings.json
 */

import type { Holding, HoldingChange } from '../types';
import { holdings as mockHoldings, holdingChanges as mockChanges } from './mockData';

// ── Types matching the merged JSON schema ────────────────────────────────────

export interface MergedHolding {
  id: number;
  institutionId: number;
  stockTicker: string;
  stockName: string;
  sector: string;
  shares: number;
  marketValue: number;
  ownershipPercent: number;
  market: 'US' | 'HK' | 'CN';
  quarter: string;
  dataSource: string;
  changeShares: number;
  changePercent: number;
}

export interface DataMeta {
  lastUpdated: string;
  totalHoldings: number;
  usHoldings: number;
  hkHoldings: number;
  cnHoldings: number;
  dataSources: string[];
  quarter: string;
}

export interface MergedData {
  meta: DataMeta;
  holdings: MergedHolding[];
  changes: HoldingChange[];
}

// ── Real data loader ──────────────────────────────────────────────────────────

let _realData: MergedData | null = null;
let _isLiveData = false;

export function getIsLiveData(): boolean {
  return _isLiveData;
}

export function getLastUpdated(): string {
  if (!_realData) return '';
  const d = new Date(_realData.meta.lastUpdated);
  const now = new Date();
  const diffMs = now.getTime() - d.getTime();
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  const diffDays = Math.floor(diffHours / 24);
  if (diffDays > 0) return `${diffDays}天前`;
  if (diffHours > 0) return `${diffHours}小时前`;
  return '刚刚';
}

export function getDataSourceLabel(): string {
  if (!_realData) return 'Mock Data';
  const sources = _realData?.meta?.dataSources ?? [];
  if (sources.includes('SEC_EDGAR')) return 'Live Data (SEC EDGAR)';
  if (sources.includes('EASTMONEY_QFII')) return 'Live Data (Eastmoney)';
  if (sources.includes('HKEX_MOCK')) return 'Demo Data';
  return 'Mock Data';
}

/**
 * Load real holdings data. Falls back to mock data on error.
 * In browser, the JSON file won't be available — use mock data.
 * In CI/GitHub Actions, the JSON file is present.
 */
export function getHoldings(): Holding[] {
  return _realData?.holdings as unknown as Holding[] ?? mockHoldings;
}

export function getHoldingChanges(): HoldingChange[] {
  return _realData?.changes ?? mockChanges;
}

export function getRealMeta(): DataMeta | null {
  return _realData?.meta ?? null;
}

// ── Try loading from bundled JSON (Vite public folder) ───────────────────────
// This works when data/merged_holdings.json is copied to public/data/

let _loadAttempted = false;

async function tryLoadBundledData(): Promise<void> {
  if (_loadAttempted) return;
  _loadAttempted = true;

  try {
    const resp = await fetch('/data/merged_holdings.json');
    if (resp.ok) {
      _realData = await resp.json();
      _isLiveData = (_realData as MergedData).meta.dataSources.some(s =>
        ['SEC_EDGAR', 'EASTMONEY_QFII', 'HKEX_MOCK'].includes(s)
      );
      console.log('[SmartMoney] Loaded real data:', (_realData as MergedData).meta);
    }
  } catch {
    // Not available in browser without the file in public/
  }
}

// Attempt auto-load on import (best-effort)
tryLoadBundledData();

// ── Fallback: complete mock data with HK + CN ───────────────────────────────

export const extendedMockHoldings: Holding[] = [
  // HK holdings for ADIA (institutionId: 9)
  {
    id: 901, institutionId: 9, stockTicker: '0700.HK', stockName: '腾讯控股',
    sector: '科技', shares: 120000000, marketValue: 5280000000,
    ownershipPercent: 1.3, market: 'HK', quarter: '2025Q4', changeShares: 8000000, changePercent: 7.1,
  },
  {
    id: 902, institutionId: 9, stockTicker: '9988.HK', stockName: '阿里巴巴',
    sector: '消费', shares: 85000000, marketValue: 7480000000,
    ownershipPercent: 3.8, market: 'HK', quarter: '2025Q4', changeShares: 5000000, changePercent: 6.3,
  },
  {
    id: 903, institutionId: 9, stockTicker: '9618.HK', stockName: '京东集团',
    sector: '消费', shares: 45000000, marketValue: 5400000000,
    ownershipPercent: 2.9, market: 'HK', quarter: '2025Q4', changeShares: -2000000, changePercent: -4.3,
  },
  {
    id: 904, institutionId: 9, stockTicker: '3690.HK', stockName: '美团',
    sector: '消费', shares: 38000000, marketValue: 4180000000,
    ownershipPercent: 2.1, market: 'HK', quarter: '2025Q4', changeShares: 3000000, changePercent: 8.6,
  },
  // HK holdings for KIA (institutionId: 10)
  {
    id: 1001, institutionId: 10, stockTicker: '0700.HK', stockName: '腾讯控股',
    sector: '科技', shares: 95000000, marketValue: 4180000000,
    ownershipPercent: 1.0, market: 'HK', quarter: '2025Q4', changeShares: 0, changePercent: 0,
  },
  {
    id: 1002, institutionId: 10, stockTicker: '9988.HK', stockName: '阿里巴巴',
    sector: '消费', shares: 62000000, marketValue: 5456000000,
    ownershipPercent: 2.8, market: 'HK', quarter: '2025Q4', changeShares: 2000000, changePercent: 3.3,
  },
  {
    id: 1003, institutionId: 10, stockTicker: '1810.HK', stockName: '小米集团',
    sector: '科技', shares: 180000000, marketValue: 2700000000,
    ownershipPercent: 5.2, market: 'HK', quarter: '2025Q4', changeShares: 15000000, changePercent: 9.1,
  },
  // CN A-share holdings for Goldman (institutionId: 3)
  {
    id: 301, institutionId: 3, stockTicker: '600519.SH', stockName: '贵州茅台',
    sector: '消费', shares: 4200000, marketValue: 7140000000,
    ownershipPercent: 3.35, market: 'CN', quarter: '2025Q4', changeShares: 300000, changePercent: 7.7,
  },
  {
    id: 302, institutionId: 3, stockTicker: '600036.SH', stockName: '招商银行',
    sector: '金融', shares: 8500000, marketValue: 3825000000,
    ownershipPercent: 4.12, market: 'CN', quarter: '2025Q4', changeShares: 500000, changePercent: 6.3,
  },
  {
    id: 303, institutionId: 3, stockTicker: '000858.SZ', stockName: '五粮液',
    sector: '消费', shares: 3200000, marketValue: 2880000000,
    ownershipPercent: 2.81, market: 'CN', quarter: '2025Q4', changeShares: -200000, changePercent: -5.9,
  },
  // CN A-share holdings for JPMorgan (institutionId: 4)
  {
    id: 401, institutionId: 4, stockTicker: '601318.SH', stockName: '中国平安',
    sector: '金融', shares: 12800000, marketValue: 8960000000,
    ownershipPercent: 6.24, market: 'CN', quarter: '2025Q4', changeShares: 800000, changePercent: 6.7,
  },
  {
    id: 402, institutionId: 4, stockTicker: '600030.SH', stockName: '中信证券',
    sector: '金融', shares: 9500000, marketValue: 4370000000,
    ownershipPercent: 5.67, market: 'CN', quarter: '2025Q4', changeShares: 1000000, changePercent: 11.8,
  },
  {
    id: 403, institutionId: 4, stockTicker: '000333.SZ', stockName: '美的集团',
    sector: '消费', shares: 6800000, marketValue: 5984000000,
    ownershipPercent: 4.89, market: 'CN', quarter: '2025Q4', changeShares: 400000, changePercent: 6.3,
  },
  {
    id: 404, institutionId: 4, stockTicker: '002415.SZ', stockName: '海康威视',
    sector: '科技', shares: 4500000, marketValue: 2295000000,
    ownershipPercent: 3.12, market: 'CN', quarter: '2025Q4', changeShares: 500000, changePercent: 12.5,
  },
];

export const extendedHoldingChanges: HoldingChange[] = [
  {
    id: 201, institutionId: 9, stockTicker: '0700.HK', stockName: '腾讯控股',
    changeType: 'increase', changePercent: 7.1, previousShares: 112000000, currentShares: 120000000, quarter: '2025Q4',
  },
  {
    id: 202, institutionId: 9, stockTicker: '3690.HK', stockName: '美团',
    changeType: 'increase', changePercent: 8.6, previousShares: 35000000, currentShares: 38000000, quarter: '2025Q4',
  },
  {
    id: 203, institutionId: 10, stockTicker: '1810.HK', stockName: '小米集团',
    changeType: 'increase', changePercent: 9.1, previousShares: 165000000, currentShares: 180000000, quarter: '2025Q4',
  },
  {
    id: 204, institutionId: 3, stockTicker: '600519.SH', stockName: '贵州茅台',
    changeType: 'increase', changePercent: 7.7, previousShares: 3900000, currentShares: 4200000, quarter: '2025Q4',
  },
  {
    id: 205, institutionId: 4, stockTicker: '600030.SH', stockName: '中信证券',
    changeType: 'increase', changePercent: 11.8, previousShares: 8500000, currentShares: 9500000, quarter: '2025Q4',
  },
  {
    id: 206, institutionId: 4, stockTicker: '002415.SZ', stockName: '海康威视',
    changeType: 'increase', changePercent: 12.5, previousShares: 4000000, currentShares: 4500000, quarter: '2025Q4',
  },
  {
    id: 207, institutionId: 9, stockTicker: '9618.HK', stockName: '京东集团',
    changeType: 'decrease', changePercent: -4.3, previousShares: 47000000, currentShares: 45000000, quarter: '2025Q4',
  },
  {
    id: 208, institutionId: 3, stockTicker: '000858.SZ', stockName: '五粮液',
    changeType: 'decrease', changePercent: -5.9, previousShares: 3400000, currentShares: 3200000, quarter: '2025Q4',
  },
];
